# Generated by Django 3.2.19 on 2023-07-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='opening_hours',
        ),
    ]
