# Generated by Django 3.2.19 on 2023-07-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_opening_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hours',
        ),
    ]
