# Generated by Django 3.2.19 on 2023-06-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230615_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customized_message',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='main_flavor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
